// Code generated by hertz generator.

package user

import (
	"github.com/cloudwego/hertz/pkg/app"
	"github.com/li1553770945/openmcp-gateway/biz/container"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _apiMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _usersMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getselfinfoMw() []app.HandlerFunc {
	// your code...
	App := container.GetGlobalContainer()
	return []app.HandlerFunc{
		App.AuthAndUserInfoMiddleware,
	}
}

func _getuserinfoMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _updateselfinfoMw() []app.HandlerFunc {
	App := container.GetGlobalContainer()
	return []app.HandlerFunc{
		App.AuthAndUserInfoMiddleware,
	}
}

func _registerMw() []app.HandlerFunc {
	// your code...
	return nil
}
