// Code generated by hertz generator.

package proxy

import (
	"context"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/li1553770945/openmcp-gateway/biz/container"
)

// Forward
// @Summary 转发请求
// @Description 转发客户端请求到目标服务,必须添加"X-OpenMCP-Token"请求头，即MCPServer生成的Token
// @Tags 转发服务
// @router /proxy [GET]
// @router /proxy [POST]
// @router /proxy [PUT]
// @router /proxy [DELETE]
// @router /proxy [PATCH]
func Forward(ctx context.Context, c *app.RequestContext) {
	container.GetGlobalContainer().ProxyService.ForwardRequest(ctx, c)
}
