// Package swagger Code generated by swaggo/swag. DO NOT EDIT
package swagger

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/auth/login": {
            "post": {
                "description": "用户使用账号密码登录",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "认证管理"
                ],
                "summary": "用户登录",
                "parameters": [
                    {
                        "description": "登录请求参数",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/auth.LoginReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "请求成功 (Code=0) 或失败 (Code!=0)",
                        "schema": {
                            "$ref": "#/definitions/auth.LoginResp"
                        }
                    }
                }
            }
        },
        "/api/auth/register": {
            "post": {
                "description": "新用户注册账号",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "认证管理"
                ],
                "summary": "用户注册",
                "parameters": [
                    {
                        "description": "注册请求参数",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/auth.RegisterReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "请求成功 (Code=0) 或失败 (Code!=0)",
                        "schema": {
                            "$ref": "#/definitions/auth.RegisterResp"
                        }
                    }
                }
            }
        },
        "/api/mcpservers": {
            "post": {
                "description": "注册一个新的 MCPServer 服务",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "MCPServer管理"
                ],
                "summary": "添加 MCPServer",
                "parameters": [
                    {
                        "description": "添加请求参数",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/mcpserver.AddMCPServerReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "请求响应 (Code=0 成功)",
                        "schema": {
                            "$ref": "#/definitions/mcpserver.AddMCPServerResp"
                        }
                    }
                }
            }
        },
        "/api/mcpservers/:id": {
            "get": {
                "description": "根据 ID 获取指定的 MCPServer 详情",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "MCPServer管理"
                ],
                "summary": "获取单个 MCPServer",
                "parameters": [
                    {
                        "type": "string",
                        "description": "MCPServer ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "请求响应 (Code=0 成功)",
                        "schema": {
                            "$ref": "#/definitions/mcpserver.GetMCPServerResp"
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "$ref": "#/definitions/mcpserver.GetMCPServerResp"
                        }
                    }
                }
            },
            "put": {
                "description": "更新指定的 MCPServer 信息",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "MCPServer管理"
                ],
                "summary": "更新 MCPServer",
                "parameters": [
                    {
                        "type": "string",
                        "description": "MCPServer ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "更新请求参数",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/mcpserver.UpdateMCPServerReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "请求响应 (Code=0 成功)",
                        "schema": {
                            "$ref": "#/definitions/mcpserver.UpdateMCPServerResp"
                        }
                    }
                }
            }
        },
        "/api/mcpservers/generate-token": {
            "post": {
                "description": "为 MCPServer 生成访问 Token",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "MCPServer管理"
                ],
                "summary": "生成 Token",
                "parameters": [
                    {
                        "description": "生成Token请求参数",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/mcpserver.GenerateTokenReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "请求响应 (Code=0 成功)",
                        "schema": {
                            "$ref": "#/definitions/mcpserver.GenerateTokenResp"
                        }
                    }
                }
            }
        },
        "/api/mcpservers/public": {
            "get": {
                "description": "获取所有公开的 MCPServer 列表",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "MCPServer管理"
                ],
                "summary": "获取公共 MCPServer 列表",
                "parameters": [
                    {
                        "type": "integer",
                        "name": "end",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "name": "start",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "请求响应 (Code=0 成功)",
                        "schema": {
                            "$ref": "#/definitions/mcpserver.GetMCPServerListResp"
                        }
                    }
                }
            }
        },
        "/api/mcpservers/self": {
            "get": {
                "description": "获取当前用户创建的 MCPServer 列表",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "MCPServer管理"
                ],
                "summary": "获取我的 MCPServer 列表",
                "parameters": [
                    {
                        "type": "integer",
                        "name": "end",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "name": "start",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "请求响应 (Code=0 成功)",
                        "schema": {
                            "$ref": "#/definitions/mcpserver.GetMCPServerListResp"
                        }
                    }
                }
            }
        },
        "/api/users/me": {
            "get": {
                "description": "获取当前登录用户的详细信息",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户管理"
                ],
                "summary": "获取当前用户信息",
                "parameters": [
                    {
                        "type": "integer",
                        "name": "userId",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "请求响应 (Code=0 成功)",
                        "schema": {
                            "$ref": "#/definitions/user.GetUserInfoResp"
                        }
                    }
                }
            }
        },
        "/api/users/user-info": {
            "get": {
                "description": "根据用户 ID 获取用户详细信息",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户管理"
                ],
                "summary": "获取用户信息",
                "parameters": [
                    {
                        "type": "integer",
                        "name": "userId",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "请求响应 (Code=0 成功)",
                        "schema": {
                            "$ref": "#/definitions/user.GetUserInfoResp"
                        }
                    }
                }
            }
        },
        "/ping": {
            "get": {
                "description": "检查服务是否存活",
                "tags": [
                    "基础接口"
                ],
                "summary": "健康检查",
                "responses": {
                    "200": {
                        "description": "Pong",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "auth.LoginReq": {
            "type": "object",
            "properties": {
                "password": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "auth.LoginResp": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {
                    "$ref": "#/definitions/auth.LoginRespData"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "auth.LoginRespData": {
            "type": "object",
            "properties": {
                "token": {
                    "type": "string"
                }
            }
        },
        "auth.RegisterReq": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "auth.RegisterResp": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "mcpserver.AddMCPServerReq": {
            "type": "object",
            "properties": {
                "description": {
                    "type": "string"
                },
                "isPublic": {
                    "type": "boolean"
                },
                "name": {
                    "type": "string"
                },
                "openProxy": {
                    "type": "boolean"
                },
                "url": {
                    "type": "string"
                }
            }
        },
        "mcpserver.AddMCPServerResp": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "mcpserver.GenerateTokenReq": {
            "type": "object",
            "properties": {
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                }
            }
        },
        "mcpserver.GenerateTokenResp": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {
                    "$ref": "#/definitions/mcpserver.GenerateTokenRespData"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "mcpserver.GenerateTokenRespData": {
            "type": "object",
            "properties": {
                "token": {
                    "type": "string"
                }
            }
        },
        "mcpserver.GetMCPServerListResp": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/mcpserver.GetMCPServerListRespData"
                    }
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "mcpserver.GetMCPServerListRespData": {
            "type": "object",
            "properties": {
                "description": {
                    "type": "string"
                },
                "isPublic": {
                    "type": "boolean"
                },
                "name": {
                    "type": "string"
                },
                "openProxy": {
                    "type": "boolean"
                },
                "url": {
                    "type": "string"
                }
            }
        },
        "mcpserver.GetMCPServerResp": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {
                    "$ref": "#/definitions/mcpserver.GetMCPServerRespData"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "mcpserver.GetMCPServerRespData": {
            "type": "object",
            "properties": {
                "description": {
                    "type": "string"
                },
                "isPublic": {
                    "type": "boolean"
                },
                "name": {
                    "type": "string"
                },
                "openProxy": {
                    "type": "boolean"
                },
                "token": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/mcpserver.TokenData"
                    }
                },
                "url": {
                    "type": "string"
                }
            }
        },
        "mcpserver.TokenData": {
            "type": "object",
            "properties": {
                "description": {
                    "type": "string"
                },
                "token": {
                    "type": "string"
                }
            }
        },
        "mcpserver.UpdateMCPServerReq": {
            "type": "object",
            "properties": {
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "isPublic": {
                    "type": "boolean"
                },
                "name": {
                    "type": "string"
                },
                "openProxy": {
                    "type": "boolean"
                },
                "url": {
                    "type": "string"
                }
            }
        },
        "mcpserver.UpdateMCPServerResp": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "user.GetUserInfoResp": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {
                    "$ref": "#/definitions/user.GetUserInfoRespData"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "user.GetUserInfoRespData": {
            "type": "object",
            "properties": {
                "nickname": {
                    "type": "string"
                },
                "role": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "OpenMCP Gateway API",
	Description:      "OpenMCP 网关服务 API 文档",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
