// Code generated by hertz generator.

package mcpserver

import (
	"context"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
	"github.com/li1553770945/openmcp-gateway/biz/constant"
	"github.com/li1553770945/openmcp-gateway/biz/container"
	mcpserver "github.com/li1553770945/openmcp-gateway/biz/model/mcpserver"
)

// AddMCPServer
// @Summary 添加 MCPServer
// @Description 注册一个新的 MCPServer 服务
// @Tags MCPServer管理
// @Accept json
// @Produce json
// @Param request body mcpserver.AddMCPServerReq true "添加请求参数"
// @Success 200 {object} mcpserver.AddMCPServerResp "请求响应 (Code=0 成功)"
// @Router /api/mcpservers [POST]
func AddMCPServer(ctx context.Context, c *app.RequestContext) {
	var err error
	var req mcpserver.AddMCPServerReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.JSON(consts.StatusOK, &mcpserver.AddMCPServerResp{
			Code:    constant.InvalidInput,
			Message: err.Error(),
		})
		return
	}

	resp := container.GetGlobalContainer().MCPServerService.AddMCPServer(ctx, &req)
	c.JSON(consts.StatusOK, resp)
}

// GenerateToken
// @Summary 生成 Token
// @Description 为 MCPServer 生成访问 Token
// @Tags MCPServer管理
// @Accept json
// @Produce json
// @Param request body mcpserver.GenerateTokenReq true "生成Token请求参数"
// @Success 200 {object} mcpserver.GenerateTokenResp "请求响应 (Code=0 成功)"
// @Router /api/mcpservers/tokens [POST]
func GenerateToken(ctx context.Context, c *app.RequestContext) {
	var err error
	var req mcpserver.GenerateTokenReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.JSON(consts.StatusOK, &mcpserver.GenerateTokenResp{
			Code:    constant.InvalidInput,
			Message: err.Error(),
		})
		return
	}

	resp := container.GetGlobalContainer().MCPServerService.GenerateToken(ctx, &req)
	c.JSON(consts.StatusOK, resp)
}

// UpdateMCPServer
// @Summary 更新 MCPServer
// @Description 更新指定的 MCPServer 信息
// @Tags MCPServer管理
// @Accept json
// @Produce json
// @Param id path string true "MCPServer ID"
// @Param request body mcpserver.UpdateMCPServerReq true "更新请求参数"
// @Success 200 {object} mcpserver.UpdateMCPServerResp "请求响应 (Code=0 成功)"
// @Router /api/mcpservers/:id [PUT]
func UpdateMCPServer(ctx context.Context, c *app.RequestContext) {
	var err error
	var req mcpserver.UpdateMCPServerReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.JSON(consts.StatusOK, &mcpserver.UpdateMCPServerResp{
			Code:    constant.InvalidInput,
			Message: err.Error(),
		})
		return
	}

	resp := container.GetGlobalContainer().MCPServerService.UpdateMCPServer(ctx, &req)
	c.JSON(consts.StatusOK, resp)
}

// GetMCPServer
// @Summary 获取单个 MCPServer
// @Description 根据 ID 获取指定的 MCPServer 详情
// @Tags MCPServer管理
// @Produce json
// @Param id path string true "MCPServer ID"
// @Success 200 {object} mcpserver.GetMCPServerResp "请求响应 (Code=0 成功)"
// @Failure 400 {object} mcpserver.GetMCPServerResp "请求参数错误"
// @Router /api/mcpservers/:id [GET]
func GetMCPServer(ctx context.Context, c *app.RequestContext) {
	var err error
	var req mcpserver.GetMCPServerReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.JSON(consts.StatusOK, &mcpserver.GetMCPServerResp{
			Code:    constant.InvalidInput,
			Message: err.Error(),
		})
		return
	}

	resp := container.GetGlobalContainer().MCPServerService.GetMCPServer(ctx, &req)
	c.JSON(consts.StatusOK, resp)
}

// DeleteMCPServer
// @Summary 删除 MCPServer
// @Description 删除指定的 MCPServer
// @Tags MCPServer管理
// @Produce json
// @Param id path string true "MCPServer ID"
// @Success 200 {object} mcpserver.DeleteMCPServerResp "请求响应 (Code=0 成功)"
// @Router /api/mcpservers/:id [DELETE]
func DeleteMCPServer(ctx context.Context, c *app.RequestContext) {
	var err error
	var req mcpserver.DeleteMCPServerReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.JSON(consts.StatusOK, &mcpserver.DeleteMCPServerResp{
			Code:    constant.InvalidInput,
			Message: err.Error(),
		})
		return
	}

	resp := container.GetGlobalContainer().MCPServerService.DeleteMCPServer(ctx, &req)
	c.JSON(consts.StatusOK, resp)
}

// DeleteToken
// @Summary 删除 Token
// @Description 删除指定的 Token
// @Tags MCPServer管理
// @Produce json
// @Param id path string true "Token ID"
// @Success 200 {object} mcpserver.DeleteTokenResp "请求响应 (Code=0 成功)"
// @Router /api/mcpservers/tokens/:id [DELETE]
func DeleteToken(ctx context.Context, c *app.RequestContext) {
	var err error
	var req mcpserver.DeleteTokenReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.JSON(consts.StatusOK, &mcpserver.DeleteTokenResp{
			Code:    constant.InvalidInput,
			Message: err.Error(),
		})
		return
	}

	resp := container.GetGlobalContainer().MCPServerService.DeleteToken(ctx, &req)
	c.JSON(consts.StatusOK, resp)
}

// GetMCPServerList
// @Summary 获取 MCPServer 列表
// @Description 获取 MCPServer 列表，通过 scope 参数区分获取自己的还是公共的
// @Tags MCPServer管理
// @Produce json
// @Param request query mcpserver.GetMCPServerListReq true "查询参数"
// @Success 200 {object} mcpserver.GetMCPServerListResp "请求响应 (Code=0 成功)"
// @Router /api/mcpservers [GET]
func GetMCPServerList(ctx context.Context, c *app.RequestContext) {
	var err error
	var req mcpserver.GetMCPServerListReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.JSON(consts.StatusOK, &mcpserver.GetMCPServerListResp{
			Code:    constant.InvalidInput,
			Message: err.Error(),
		})
		return
	}

	resp := container.GetGlobalContainer().MCPServerService.GetMCPServerList(ctx, &req)
	c.JSON(consts.StatusOK, resp)
}
