// Code generated by hertz generator.

package mcpserver

import (
	"context"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
	mcpserver "github.com/li1553770945/openmcp-gateway/biz/model/mcpserver"
)

// AddMCPServer .
// @router /api/mcpserver [POST]
func AddMCPServer(ctx context.Context, c *app.RequestContext) {
	var err error
	var req mcpserver.AddMCPServerReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(mcpserver.AddMCPServerResp)

	c.JSON(consts.StatusOK, resp)
}
