// Code generated by hertz generator.

package main

import (
	"net"
	"os"

	"github.com/cloudwego/hertz/pkg/app/server"
	"github.com/li1553770945/openmcp-gateway/biz/container"
)

func main() {
	env := os.Getenv("ENV")
	if env == "" {
		panic("请通过`export ENV=development或production设置当前环境`")
	}
	container.InitContainer(env)

	App := container.GetGlobalContainer()
	addr, err := net.ResolveTCPAddr("tcp", App.Config.ServerConfig.HttpServerListenAddress)
	if err != nil {
		panic("设置监听地址出错")
	}
	h := server.Default(server.WithHostPorts(addr.String()))

	register(h)
	h.Spin()
}
