// Code generated by hertz generator.

// @title           OpenMCP Gateway API
// @version         1.0
// @description     OpenMCP 网关服务 API 文档
// @BasePath        /
package main

import (
	"context"
	"net"
	"os"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/app/server"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
	"github.com/hertz-contrib/swagger"
	"github.com/li1553770945/openmcp-gateway/biz/container"

	_ "github.com/li1553770945/openmcp-gateway/docs/swagger"
	swaggerFiles "github.com/swaggo/files"
)

func main() {
	env := os.Getenv("ENV")
	if env == "" {
		panic("请通过`export ENV=development或production设置当前环境`")
	}
	container.InitContainer(env)

	App := container.GetGlobalContainer()
	addr, err := net.ResolveTCPAddr("tcp", App.Config.ServerConfig.HttpServerListenAddress)
	if err != nil {
		panic("设置监听地址出错")
	}
	h := server.Default(server.WithHostPorts(addr.String()))

	// 使用相对路径，这样无论端口怎么变，浏览器都会基于当前访问地址去加载 doc.json
	url := swagger.URL("/docs/doc.json")
	h.GET("/docs", func(ctx context.Context, c *app.RequestContext) {
		c.Redirect(consts.StatusMovedPermanently, []byte("/docs/index.html"))
	})
	h.GET("/docs/*any", swagger.WrapHandler(swaggerFiles.Handler, url))
	register(h)
	h.Spin()
}
