// Code generated by hertz generator.

package mcpserver

import (
	"github.com/cloudwego/hertz/pkg/app"
	"github.com/li1553770945/openmcp-gateway/biz/container"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _apiMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _addmcpserverMw() []app.HandlerFunc {
	return []app.HandlerFunc{
		container.GetGlobalContainer().AuthAndUserInfoMiddleware,
	}
}

func _mcpserversMw() []app.HandlerFunc {
	return []app.HandlerFunc{
		container.GetGlobalContainer().AuthAndUserInfoMiddleware,
	}
}

func _generatetokenMw() []app.HandlerFunc {
	return []app.HandlerFunc{
		container.GetGlobalContainer().AuthAndUserInfoMiddleware,
	}
}

func _getmcpserverMw() []app.HandlerFunc {
	return []app.HandlerFunc{
		container.GetGlobalContainer().AuthAndUserInfoMiddleware,
	}
}

func _updatemcpserverMw() []app.HandlerFunc {
	return []app.HandlerFunc{
		container.GetGlobalContainer().AuthAndUserInfoMiddleware,
	}
}

func _deletemcpserverMw() []app.HandlerFunc {
	return []app.HandlerFunc{
		container.GetGlobalContainer().AuthAndUserInfoMiddleware,
	}
}

func _tokenMw() []app.HandlerFunc {
	return []app.HandlerFunc{
		container.GetGlobalContainer().AuthAndUserInfoMiddleware,
	}
}

func _deletetokenMw() []app.HandlerFunc {
	return []app.HandlerFunc{
		container.GetGlobalContainer().AuthAndUserInfoMiddleware,
	}
}

func _tokensMw() []app.HandlerFunc {
	return []app.HandlerFunc{
		container.GetGlobalContainer().AuthAndUserInfoMiddleware,
	}
}

func _getmcpserverlistMw() []app.HandlerFunc {
	return []app.HandlerFunc{
		container.GetGlobalContainer().AuthAndUserInfoMiddleware,
	}
}

func _mcpservers0Mw() []app.HandlerFunc {
	return []app.HandlerFunc{
		container.GetGlobalContainer().AuthAndUserInfoMiddleware,
	}
}
