// Code generated by hertz generator.

package mcpserver

import (
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _apiMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _addmcpserverMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _mcpserversMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _generatetokenMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getmcpserverMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getpublicmcpserverlistMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getselfmcpserverlistMw() []app.HandlerFunc {
	// your code...
	return nil
}
