// Code generated by hertz generator.

package proxy

import (
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _forwardMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _proxyMw() []app.HandlerFunc {
	// your code...
	return nil
}
