// Code generated by hertz generator.

package user

import (
	"context"
	"fmt"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
	"github.com/li1553770945/openmcp-gateway/biz/constant"
	"github.com/li1553770945/openmcp-gateway/biz/container"
	user "github.com/li1553770945/openmcp-gateway/biz/model/user"
)

// GetUserInfo .
// @router /api/users/user-info [GET]
func GetUserInfo(ctx context.Context, c *app.RequestContext) {
	var err error
	var req user.GetUserInfoReq
	err = c.BindAndValidate(&req)
	if err != nil {
		resp := user.GetUserInfoResp{
			Code:    constant.InvalidInput,
			Message: fmt.Sprintf("请求参数错误:%s", err.Error()),
		}
		c.JSON(consts.StatusOK, resp)
		return
	}

	App := container.GetGlobalContainer()
	resp := App.UserService.GetUserInfo(ctx, &req)

	c.JSON(consts.StatusOK, resp)
}

// GetSelfInfo .
// @router /api/users/me [GET]
func GetSelfInfo(ctx context.Context, c *app.RequestContext) {
	var err error
	var req user.GetUserInfoReq
	err = c.BindAndValidate(&req)
	if err != nil {
		resp := user.GetUserInfoResp{
			Code:    constant.InvalidInput,
			Message: fmt.Sprintf("请求参数错误:%s", err.Error()),
		}
		c.JSON(consts.StatusOK, resp)
		return
	}

	resp := new(user.GetUserInfoResp)

	c.JSON(consts.StatusOK, resp)
}
