// Code generated by hertz generator.

package auth

import (
	"context"
	"fmt"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
	"github.com/li1553770945/openmcp-gateway/biz/constant"
	"github.com/li1553770945/openmcp-gateway/biz/container"
	auth "github.com/li1553770945/openmcp-gateway/biz/model/auth"
)

// Login
// @Summary 用户登录
// @Description 用户使用账号密码登录
// @Tags 认证管理
// @Accept json
// @Produce json
// @Param request body auth.LoginReq true "登录请求参数"
// @Success 200 {object} auth.LoginResp "请求成功 (Code=0) 或失败 (Code!=0)"
// @Router /api/auth/login [POST]
func Login(ctx context.Context, c *app.RequestContext) {
	var err error
	var req auth.LoginReq
	err = c.BindAndValidate(&req)
	if err != nil {
		resp := auth.LoginResp{
			Code:    constant.InvalidInput,
			Message: fmt.Sprintf("请求参数错误:%s", err.Error()),
		}
		c.JSON(consts.StatusOK, resp)
		return
	}

	App := container.GetGlobalContainer()
	resp, err := App.AuthService.Login(ctx, &req)
	if err != nil {
		resp := auth.LoginResp{
			Code:    constant.SystemError,
			Message: err.Error(),
		}
		c.JSON(consts.StatusOK, resp)
		return
	}

	c.JSON(consts.StatusOK, resp)
}
