// Code generated by hertz generator. DO NOT EDIT.

package router

import (
	"github.com/cloudwego/hertz/pkg/app/server"
	auth "github.com/li1553770945/openmcp-gateway/biz/router/auth"
	mcpserver "github.com/li1553770945/openmcp-gateway/biz/router/mcpserver"
	proxy "github.com/li1553770945/openmcp-gateway/biz/router/proxy"
	user "github.com/li1553770945/openmcp-gateway/biz/router/user"
)

// GeneratedRegister registers routers generated by IDL.
func GeneratedRegister(r *server.Hertz) {
	//INSERT_POINT: DO NOT DELETE THIS LINE!
	proxy.Register(r)

	user.Register(r)

	mcpserver.Register(r)

	auth.Register(r)

}
